***
# 2. Introduction to Python in Jupyter - The basics - Part I
>-basic coding (accessing directories, commenting, help,...) <br>
-relative file paths <br>
-indentation
***

## 2.1 Basic coding tips

In [1]:
# Use the number symbol to comment your code
# If you want to comment multiple lines, you can select all the lines and do: CRTL and /
# Undo commenting by selecting the lines and do CTRL and / again

# Use the back slash to split a long code in parts
# For example

a1 = '1' + '2' + '3' + \
    '4' + '5'

# is the same as 


a2 = ('1' + '2' + '3' +
    '4' + '5')

In [2]:
print (a1)
print (a2)

12345
12345

In [3]:
# But this will give an error
a3 = '1' + '2' + '3' + 
    '4' + '5'

print(a3)

SyntaxError: invalid syntax (3041281332.py, line 2)

In [ ]:
# !pwd shows you the location of your current file
# You use ! to run terminal commands (from the underlying system)

!pwd

In [ ]:
# Some other terminal commands 
# Both comments show a list of files in the directory
!ls
!dir

In [ ]:
# You could also use the a Python function to see your working directory
# You would need to import a specific module for this

import os
os.getcwd()

In [4]:
# This is how you ask for help
?

IPython -- An enhanced Interactive Python
=========================================

IPython offers a fully compatible replacement for the standard Python
interpreter, with convenient shell features, special commands, command
history mechanism and output results caching.

At your system command line, type 'ipython -h' to see the command line
options available. This document only describes interactive features.

GETTING HELP
------------

Within IPython you have various way to access help:

  ?         -> Introduction and overview of IPython's features (this screen).
  object?   -> Details about 'object'.
  object??  -> More detailed, verbose information about 'object'.
  %quickref -> Quick reference of all IPython specific syntax and magics.
  help      -> Access Python's own help system.

If you are in terminal IPython you can quit this screen by pressing `q`.


MAIN FEATURES
-------------

* Access to the standard Python help with object docstrings and the Python
  manuals. Simply type 'help' (no quotes) to invoke it.

* Magic commands: type %magic for information on the magic subsystem.

* System command aliases, via the %alias command or the configuration file(s).

* Dynamic object information:

  Typing ?word or word? prints detailed information about an object. Certain
  long strings (code, etc.) get snipped in the center for brevity.

  Typing ??word or word?? gives access to the full information without
  snipping long strings. Strings that are longer than the screen are printed
  through the less pager.

  The ?/?? system gives access to the full source code for any object (if
  available), shows function prototypes and other useful information.

  If you just want to see an object's docstring, type '%pdoc object' (without
  quotes, and without % if you have automagic on).

* Tab completion in the local namespace:

  At any time, hitting tab will complete any available python commands or
  variable names, and show you a list of the possible completions if there's
  no unambiguous one. It will also complete filenames in the current directory.

* Search previous command history in multiple ways:

  - Start typing, and then use arrow keys up/down or (Ctrl-p/Ctrl-n) to search
    through the history items that match what you've typed so far.

  - Hit Ctrl-r: opens a search prompt. Begin typing and the system searches
    your history for lines that match what you've typed so far, completing as
    much as it can.

  - %hist: search history by index.

* Persistent command history across sessions.

* Logging of input with the ability to save and restore a working session.

* System shell with !. Typing !ls will run 'ls' in the current directory.

* The reload command does a 'deep' reload of a module: changes made to the
  module since you imported will actually be available without having to exit.

* Verbose and colored exception traceback printouts. See the magic xmode and
  xcolor functions for details (just type %magic).

* Input caching system:

  IPython offers numbered prompts (In/Out) with input and output caching. All
  input is saved and can be retrieved as variables (besides the usual arrow
  key recall).

  The following GLOBAL variables always exist (so don't overwrite them!):
  _i: stores previous input.
  _ii: next previous.
  _iii: next-next previous.
  _ih : a list of all input _ih[n] is the input from line n.

  Additionally, global variables named _i<n> are dynamically created (<n>
  being the prompt counter), such that _i<n> == _ih[<n>]

  For example, what you typed at prompt 14 is available as _i14 and _ih[14].

  You can create macros which contain multiple input lines from this history,
  for later re-execution, with the %macro function.

  The history function %hist allows you to see any part of your input history
  by printing a range of the _i variables. Note that inputs which contain
  magic functions (%) appear in the history with a prepended comment. This is
  because they aren't really valid Python code, so you can't exec them.

* Output caching system:

  For output that is returned from actions, a system similar to the input
  cache exists but using _ instead of _i. Only actions that produce a result
  (NOT assignments, for example) are cached. If you are familiar with
  Mathematica, IPython's _ variables behave exactly like Mathematica's %
  variables.

  The following GLOBAL variables always exist (so don't overwrite them!):
  _ (one underscore): previous output.
  __ (two underscores): next previous.
  ___ (three underscores): next-next previous.

  Global variables named _<n> are dynamically created (<n> being the prompt
  counter), such that the result of output <n> is always available as _<n>.

  Finally, a global dictionary named _oh exists with entries for all lines
  which generated output.

* Directory history:

  Your history of visited directories is kept in the global list _dh, and the
  magic %cd command can be used to go to any entry in that list.

* Auto-parentheses and auto-quotes (adapted from Nathan Gray's LazyPython)

  1. Auto-parentheses

     Callable objects (i.e. functions, methods, etc) can be invoked like
     this (notice the commas between the arguments)::

         In [1]: callable_ob arg1, arg2, arg3

     and the input will be translated to this::

         callable_ob(arg1, arg2, arg3)

     This feature is off by default (in rare cases it can produce
     undesirable side-effects), but you can activate it at the command-line
     by starting IPython with `--autocall 1`, set it permanently in your
     configuration file, or turn on at runtime with `%autocall 1`.

     You can force auto-parentheses by using '/' as the first character
     of a line.  For example::

          In [1]: /globals             # becomes 'globals()'

     Note that the '/' MUST be the first character on the line!  This
     won't work::

          In [2]: print /globals    # syntax error

     In most cases the automatic algorithm should work, so you should
     rarely need to explicitly invoke /. One notable exception is if you
     are trying to call a function with a list of tuples as arguments (the
     parenthesis will confuse IPython)::

          In [1]: zip (1,2,3),(4,5,6)  # won't work

     but this will work::

          In [2]: /zip (1,2,3),(4,5,6)
          ------> zip ((1,2,3),(4,5,6))
          Out[2]= [(1, 4), (2, 5), (3, 6)]

     IPython tells you that it has altered your command line by
     displaying the new command line preceded by -->.  e.g.::

          In [18]: callable list
          -------> callable (list)

  2. Auto-Quoting

     You can force auto-quoting of a function's arguments by using ',' as
     the first character of a line.  For example::

          In [1]: ,my_function /home/me   # becomes my_function("/home/me")

     If you use ';' instead, the whole argument is quoted as a single
     string (while ',' splits on whitespace)::

          In [2]: ,my_function a b c   # becomes my_function("a","b","c")
          In [3]: ;my_function a b c   # becomes my_function("a b c")

     Note that the ',' MUST be the first character on the line!  This
     won't work::

          In [4]: x = ,my_function /home/me    # syntax error

In [5]:
# This is how to ask for help about a module (same for functions, packages, etc)
os?

Object `os` not found.

***
## 2.2 Relative file paths

### **Always** store your data and resources in the same folder (or subfolder) as your .ipynb file (your jupyter notebook)! 
### And always use relative paths 
If you have a Jupyter notebook that uses a specific dataset, make sure that you save the data in the same folder as your notebook.<br>
If you work from a local drive, in Windows (or any other OS), you would usually copy the file path directly from your `File explorer.` <br>
In Windows, it would like this: `C:\Training\data\myData.csv` <br>

Windows uses a backslash character between folder names (most other operating systems use a forward slash). <br>
If you define a file path with backslashes in python, you will get an error, python will not find your file. <br>
Why? Well, Python has special uses for the backslash in combination with certain characters (for example /n means next line, and their are other uses, but who would memorize those right!?!) <br>

#### **So how do we solve this?**

**There are 3 "manual" ways:**
1. double all your back slashes, so `C:\Training\data\myData.csv` would become `C:\\Training\\data\\myData.csv`
2. change you backslashes into forward slashes, so `C:\Training\data\myData.csv` would become `C:/Training/data/myData.csv`
3. Ugh...Imagine you have 100 filepaths with 20 backslashes to convert. Ok, maybe you could do a find and subsitute. OR, you can use the r! <br>
    -Would look like this file = `r'C:\Training\data\myData.csv'` or  `r"C:\Training\data\myData.csv"`
    
*Let's look at these manual solutions!*

In [6]:
# First, we need to import a few libraries to be able to read the data
import numpy as np # numpy is a python library for working with arrays, if you want more info about it write np? in a code cell.
import pandas as pd # for data analysis, for more info write pd? in a code cell.

In [7]:
pd?

Type:        module
String form: <module 'pandas' from '/opt/conda/lib/python3.9/site-packages/pandas/__init__.py'>
File:        /opt/conda/lib/python3.9/site-packages/pandas/__init__.py
Docstring:
pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

In [8]:
# We will read the file called climate.csv in the data folder
# First, we will assign the full filename to a variable, file
# Note that I have changed the slashes to forward slashes
file = "./data/climate.csv"

In [9]:
# Now we read this variable using the panda read csv function
# The data will be saved within the variable called inClimate
inClimate = pd.read_csv(
    file, skiprows=np.arange(0, 0), na_values="-99.99"
)

In [10]:
# Just type the variable name to display the data
# One year of weather data for a randomly choosed weather station in Quebec
inClimate

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-01,2010,1,1,NaN,-3.0,...,4.0,NaN,4.0,NaN,26.0,NaN,NaN,NaN,NaN,NaN
1,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-02,2010,1,2,NaN,-8.0,...,10.0,NaN,10.0,NaN,27.0,NaN,NaN,NaN,NaN,NaN
2,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-03,2010,1,3,NaN,-5.0,...,5.0,NaN,5.0,NaN,35.0,NaN,NaN,NaN,NaN,NaN
3,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-04,2010,1,4,NaN,-7.0,...,0.0,T,0.0,T,NaN,M,NaN,NaN,NaN,NaN
4,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-05,2010,1,5,NaN,-5.5,...,0.0,NaN,0.0,NaN,35.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-27,2010,12,27,NaN,-10.5,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
361,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-28,2010,12,28,NaN,-4.0,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
362,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-29,2010,12,29,NaN,0.0,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
363,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-30,2010,12,30,NaN,1.5,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
364,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-31,2010,12,31,NaN,5.0,...,0.0,NaN,2.0,NaN,18.0,NaN,NaN,NaN,NaN,NaN

**If we would would use the back slashes for the filepath, you would get an error. <br>If you use the forward slash, double back slash or r '',
the code would run ok**

**There are at least two solutions that use specific libraries that will work on both Windows and Mac machines:**
1. os.path.join() <br>
import os.path <br>
data_folder = os.path.join("source_data", "text_files") <br>
file_to_open = os.path.join(data_folder, "raw_data.txt") <br>
f = open(file_to_open)

2. A shorter syntax would be by using python's pathlib library
from pathlib import Path <br>
data_folder = Path("source_data/text_files/") <br>
file_to_open = data_folder / "raw_data.txt" <br>
f = open(file_to_open)

In [11]:
# We will try the first method
# Start by importing the relevant library
import os.path

In [12]:
#Use the function to create the filepath, display the data
data_folder = os.path.join("data")
file_to_open = os.path.join(data_folder, "climate.csv")
f1 = open(file_to_open)
inClimate1 = pd.read_csv(
    f1, skiprows=np.arange(0, 0), na_values="-99.99"
)
inClimate1

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-01,2010,1,1,NaN,-3.0,...,4.0,NaN,4.0,NaN,26.0,NaN,NaN,NaN,NaN,NaN
1,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-02,2010,1,2,NaN,-8.0,...,10.0,NaN,10.0,NaN,27.0,NaN,NaN,NaN,NaN,NaN
2,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-03,2010,1,3,NaN,-5.0,...,5.0,NaN,5.0,NaN,35.0,NaN,NaN,NaN,NaN,NaN
3,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-04,2010,1,4,NaN,-7.0,...,0.0,T,0.0,T,NaN,M,NaN,NaN,NaN,NaN
4,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-05,2010,1,5,NaN,-5.5,...,0.0,NaN,0.0,NaN,35.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-27,2010,12,27,NaN,-10.5,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
361,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-28,2010,12,28,NaN,-4.0,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
362,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-29,2010,12,29,NaN,0.0,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
363,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-30,2010,12,30,NaN,1.5,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
364,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-31,2010,12,31,NaN,5.0,...,0.0,NaN,2.0,NaN,18.0,NaN,NaN,NaN,NaN,NaN

In [13]:
# And the second method
# Start by importing the relevant library
from pathlib import Path

In [14]:
#Use the function to create the filepath, display the data
data_folder = Path("data")
file_to_open = data_folder / "climate.csv"
f2 = open(file_to_open)
inClimate2 = pd.read_csv(
    f2, skiprows=np.arange(0, 0), na_values="-99.99"
)
inClimate2

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-01,2010,1,1,NaN,-3.0,...,4.0,NaN,4.0,NaN,26.0,NaN,NaN,NaN,NaN,NaN
1,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-02,2010,1,2,NaN,-8.0,...,10.0,NaN,10.0,NaN,27.0,NaN,NaN,NaN,NaN,NaN
2,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-03,2010,1,3,NaN,-5.0,...,5.0,NaN,5.0,NaN,35.0,NaN,NaN,NaN,NaN,NaN
3,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-04,2010,1,4,NaN,-7.0,...,0.0,T,0.0,T,NaN,M,NaN,NaN,NaN,NaN
4,-74.17,45.32,COTEAU DU LAC,7011947,2010-01-05,2010,1,5,NaN,-5.5,...,0.0,NaN,0.0,NaN,35.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-27,2010,12,27,NaN,-10.5,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
361,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-28,2010,12,28,NaN,-4.0,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
362,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-29,2010,12,29,NaN,0.0,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
363,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-30,2010,12,30,NaN,1.5,...,0.0,NaN,0.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN
364,-74.17,45.32,COTEAU DU LAC,7011947,2010-12-31,2010,12,31,NaN,5.0,...,0.0,NaN,2.0,NaN,18.0,NaN,NaN,NaN,NaN,NaN

***
## 2.3 Indentation
Python uses `indentation` to highlight blocks of code. Whitespace is used for indentation in Python (you determine the number of white spaces your self). <br>
All statements with the same distance to the right belong to the same block of code (compared to `curly braces` in r for example).

Python will notify you (error) in the case of obvious mismatching indentation. But you won't get a warning when there is no structural mismatch. <br>
Which can be become very problematic.

**Let's look at a few examples to illustrate this!**

***
*First example below shows the right code!
You want to calculate the factors of a specific number.*

In [18]:
# Define a function to calculate the factors of a number
# The name of the function is get_factors

def get_factors1(num):
    df=open('factorsCorrect.txt','w')
    for i in range(1, num + 1):
        if num % i == 0:
            print("{} is a factor of {}.".format(i, num))
            df.write(str(i))
            df.write('\n') # write the results of the function to a file on disk
    df.close

In [19]:
get_factors1(10) # Run the function to find out what the factors are of 10

1 is a factor of 10.
2 is a factor of 10.
5 is a factor of 10.
10 is a factor of 10.

***
*Second example below shows the code with an obvious mismatch!<br>
`You will get an error message`.*

In [20]:
# Define a function to calculate the factors of a number
# The name of the function is get_factors
# The code has an obvious indentation mismatch. After the <for loop> starts, a new block is expected!

def get_factors2(num):
    df=open('factorsError1.txt','w')
    for i in range(1, num + 1):
        if num % i == 0:
        print("{} is a factor of {}.".format(i, num)) #this is an obvious indentation error, because an indented block is expected after the FOR loop
            df.write(str(i))
            df.write('\n')  # write the results of the function to a file on disk
    df.close

IndentationError: expected an indented block (1565662213.py, line 9)

In [21]:
get_factors2(10)

NameError: name 'get_factors2' is not defined

***
*Third example below shows the code with an indentation error that will not be captured by python!<br>
You will NOT get an error message, yet the result will be wrong.*

In [22]:
def get_factors3(num):
    df=open('factorsError2.txt','w')
    for i in range(1, num + 1):
        if num % i == 0:
            print("{} is a factor of {}.".format(i, num))
        df.write(str(i))  # This line (and the next) is part of the IF block, but was accidently moved to the FOR block. Answers will be wrong, but nothing wrong syntax wise!!
        df.write('\n')  # write the results of the function to a file on disk
    df.close

In [23]:
get_factors3(10)
# The print results look okay. But check your factorsError2.txt file!!!

1 is a factor of 10.
2 is a factor of 10.
5 is a factor of 10.
10 is a factor of 10.

***
*Fourth example below shows the code with another indentation error that will not be captured by python!<br>
You will NOT get an error message, yet the result will be wrong.*

In [24]:
def get_factors4(num):
    df=open('factorsError3.txt','w')
    for i in range(1, num + 1):
        if num % i == 0:
            print("{} is a factor of {}.".format(i, num)) # This line is part of the IF block, but was accidently moved to the Function block. Answers will be wrong, but nothing wrong syntax wise!!
    df.write(str(i))
    df.write('\n')  # write the results of the function to a file on disk
    df.close

In [25]:
get_factors4(10)
# The print results look okay. But check your factorsError3.txt file!!!

1 is a factor of 10.
2 is a factor of 10.
5 is a factor of 10.
10 is a factor of 10.

***
### Pay attention to your indentations in Python!!!
***